---
version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
    #Mapeie seu volume aqui#
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SERVER_PROTOCOL=http
      - GF_HOST=
      - GF_PORT=3000
      - GF_LOG_MODE=syslog console
      - GF_DATABASE_NAME=
      - GF_DATABASE_USER=
      - GF_DATABASE_PASSWORD=
#     - GF_CERT_FILE=/path/to/crt
#     - GF_CERT_KEY=/path/to/key
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource, radensolutions-netxms-datasource, marcusolsson-treemap-panel, blackmirror1-singlestat-math-panel
    user: "0" # The Grafana Docker image runs with the root group (id 0) instead of the grafana group (id 472), for better compatibility with OpenShift. If you extend the official Docker image you may need to change your scripts to use the root group instead of grafana https://grafana.com/docs/grafana/latest/installation/docker/